PAPER_SECTIONS = [
    # "Abstract",
    "Introduction",
    # "Background",
    "Methods",
    "Results",
    "Discussion",
    "Conclusion",
    # "Summary",
]
# TODO These need to be aligned with concept config sections

# Each model is available in its own region:

GEMINI_FLASH_MODELS = [
    ("gemini-1.5-flash", "europe-west4"),
    ("gemini-1.5-flash", "asia-east1"),
    ("gemini-1.5-flash", "asia-east2"),
    ("gemini-1.5-flash", "asia-northeast1"),
    ("gemini-1.5-flash", "asia-northeast3"),
    ("gemini-1.5-flash", "asia-south1"),
    ("gemini-1.5-flash", "asia-southeast1"),
    ("gemini-1.5-flash", "australia-southeast1"),
    ("gemini-1.5-flash", "europe-central2"),
    ("gemini-1.5-flash", "europe-north1"),
    ("gemini-1.5-flash", "europe-southwest1"),
    ("gemini-1.5-flash", "europe-west1"),
    ("gemini-1.5-flash", "europe-west2"),
    ("gemini-1.5-flash", "europe-west3"),
    ("gemini-1.5-flash", "europe-west6"),
    ("gemini-1.5-flash", "europe-west8"),
    ("gemini-1.5-flash", "europe-west9"),
    ("gemini-1.5-flash", "me-central1"),
    ("gemini-1.5-flash", "me-central2"),
    ("gemini-1.5-flash", "me-west1"),
    ("gemini-1.5-flash", "northamerica-northeast1"),
    ("gemini-1.5-flash", "southamerica-east1"),
    ("gemini-1.5-flash", "us-central1"),
    ("gemini-1.5-flash", "us-east1"),
    ("gemini-1.5-flash", "us-east4"),
    ("gemini-1.5-flash", "us-east5"),
    ("gemini-1.5-flash", "us-south1"),
    ("gemini-1.5-flash", "us-west1"),
    ("gemini-1.5-flash", "us-west4"),
]

GEMINI_PRO_MODELS = [
    ("gemini-pro", "asia-east1"),
    ("gemini-pro", "asia-east2"),
    ("gemini-pro", "asia-northeast1"),
    ("gemini-pro", "asia-northeast3"),
    ("gemini-pro", "asia-south1"),
    ("gemini-pro", "asia-southeast1"),
    ("gemini-pro", "australia-southeast1"),
    ("gemini-pro", "europe-central2"),
    ("gemini-pro", "europe-north1"),
    ("gemini-pro", "europe-southwest1"),
    ("gemini-pro", "europe-west1"),
    ("gemini-pro", "europe-west2"),
    ("gemini-pro", "europe-west3"),
    ("gemini-pro", "europe-west4"),
    ("gemini-pro", "europe-west6"),
    ("gemini-pro", "europe-west8"),
    ("gemini-pro", "europe-west9"),
    ("gemini-pro", "me-central1"),
    ("gemini-pro", "me-central2"),
    ("gemini-pro", "me-west1"),
    ("gemini-pro", "northamerica-northeast1"),
    ("gemini-pro", "southamerica-east1"),
    ("gemini-pro", "us-central1"),
    ("gemini-pro", "us-east1"),
    ("gemini-pro", "us-east4"),
    ("gemini-pro", "us-east5"),
    ("gemini-pro", "us-south1"),
    ("gemini-pro", "us-west1"),
    ("gemini-pro", "us-west4"),
]

GEMINI_15_PRO_MODELS = [
    ("gemini-1.5-pro", "asia-east1"),
    ("gemini-1.5-pro", "asia-east2"),
    ("gemini-1.5-pro", "asia-northeast1"),
    ("gemini-1.5-pro", "asia-northeast3"),
    ("gemini-1.5-pro", "asia-south1"),
    ("gemini-1.5-pro", "asia-southeast1"),
    ("gemini-1.5-pro", "australia-southeast1"),
    ("gemini-1.5-pro", "europe-central2"),
    ("gemini-1.5-pro", "europe-north1"),
    ("gemini-1.5-pro", "europe-southwest1"),
    ("gemini-1.5-pro", "europe-west1"),
    ("gemini-1.5-pro", "europe-west2"),
    ("gemini-1.5-pro", "europe-west3"),
    ("gemini-1.5-pro", "europe-west4"),
    ("gemini-1.5-pro", "europe-west6"),
    ("gemini-1.5-pro", "europe-west8"),
    ("gemini-1.5-pro", "europe-west9"),
    ("gemini-1.5-pro", "me-central1"),
    ("gemini-1.5-pro", "me-central2"),
    ("gemini-1.5-pro", "me-west1"),
    ("gemini-1.5-pro", "northamerica-northeast1"),
    ("gemini-1.5-pro", "southamerica-east1"),
    ("gemini-1.5-pro", "us-central1"),
    ("gemini-1.5-pro", "us-east1"),
    ("gemini-1.5-pro", "us-east4"),
    ("gemini-1.5-pro", "us-east5"),
    ("gemini-1.5-pro", "us-south1"),
    ("gemini-1.5-pro", "us-west1"),
    ("gemini-1.5-pro", "us-west4"),
]
GEMINI_FLASH_8B_MODELS = [
    ("gemini-1.5-flash-8b", "asia-east1"),
    ("gemini-1.5-flash-8b", "asia-east2"),
    ("gemini-1.5-flash-8b", "asia-northeast1"),
    ("gemini-1.5-flash-8b", "asia-northeast3"),
    ("gemini-1.5-flash-8b", "asia-south1"),
    ("gemini-1.5-flash-8b", "asia-southeast1"),
    ("gemini-1.5-flash-8b", "australia-southeast1"),
    ("gemini-1.5-flash-8b", "europe-central2"),
    ("gemini-1.5-flash-8b", "europe-north1"),
    ("gemini-1.5-flash-8b", "europe-southwest1"),
    ("gemini-1.5-flash-8b", "europe-west1"),
    ("gemini-1.5-flash-8b", "europe-west2"),
    ("gemini-1.5-flash-8b", "europe-west3"),
    ("gemini-1.5-flash-8b", "europe-west4"),
    ("gemini-1.5-flash-8b", "europe-west6"),
    ("gemini-1.5-flash-8b", "europe-west8"),
    ("gemini-1.5-flash-8b", "europe-west9"),
    ("gemini-1.5-flash-8b", "me-central1"),
    ("gemini-1.5-flash-8b", "me-central2"),
    ("gemini-1.5-flash-8b", "me-west1"),
    ("gemini-1.5-flash-8b", "northamerica-northeast1"),
    ("gemini-1.5-flash-8b", "southamerica-east1"),
    ("gemini-1.5-flash-8b", "us-central1"),
    ("gemini-1.5-flash-8b", "us-east1"),
    ("gemini-1.5-flash-8b", "us-east4"),
    ("gemini-1.5-flash-8b", "us-east5"),
    ("gemini-1.5-flash-8b", "us-south1"),
    ("gemini-1.5-flash-8b", "us-west1"),
    ("gemini-1.5-flash-8b", "us-west4"),
]
